### ISSUE TITLE
Can we get new bsb bundles in static

### ISSUE THREAD

**Issue by Schmavery** [jaredly/redoc#24]
https://github.com/jaredly/redoc/tree/master/static seems to only go up to bs-3.0.0.js, which as far as I can tell, is preventing the docs from being editable when I generate them. How can we generate new ones (for 4.0.6, for example)?

**Comment by jaredly** [comment]
Got 4.0.18 going

**Comment by jaredly** [comment]
The way I generate them:
on this fork, in this directory `https://github.com/jaredly/bucklescript/tree/playground-now/playground`, run `esy` and then `esy js`.
You have to have run a release build so that you have all the cmi's available to you... I think...
